def get_body_region_by_id(id):
    map={
        235: 'Back Top of Head',
        236: 'Left Back of Head',
        237: 'Right Back of Head',
        238: 'Back Neck',
        239: 'Back Left Shoulder',
        240: 'Back Right Shoulder',
        241: 'Back Left Shoulder Joint',
        242: 'Back Right Shoulder Joint',
        243: 'Left Arm Over',
        244: 'Upper Left Back',
        245: 'Upper Right Back',
        246: 'Right Arm Over',
        247: 'Upper Middle Back',
        248: 'Lower Middle Back',
        249: 'Lower Left Back',
        250: 'Lower Right Back',
        251: 'Back Left Elbow',
        252: 'Back Right Elbow',
        253: 'Left Arm Under',
        254: 'Buttock',
        255: 'Right Arm Under',
        256: 'Back Left Wrist',
        257: 'Back Right Wrist',
        258: 'Back Left Hand',
        259: 'Back Left Upper Thigh',
        260: 'Back Right Upper Thigh',
        261: 'Back Right Hand',
        262: 'Back Left Lower Thigh',
        263: 'Back Right Lower Thigh',
        264: 'Left Back Knee',
        265: 'Right Back Knee',
        266: 'Back Left Calf',
        267: 'Back Right Calf',
        268: 'Back Left Ankle',
        269: 'Back Right Ankle',
        270: 'Back Left Foot',
        271: 'Back Right Foot',

        219: 'Left Posterior Lower Back',
        220: 'Left Sacrum',
        221: 'Right Sacrum',
        222: 'Right Posterior Lower Back',
        223: 'Left Superior Lateral Buttock',
        224: 'Left Superior Medial Buttock',
        225: 'Superior Gluteal',
        226: 'Inferior Gluteal',
        227: 'Right Superior Medial Buttock',
        228: 'Right Superior Lateral Buttock',
        229: 'Left Inferior Lateral Buttock',
        230: 'Left Inferior Medial Buttock',
        231: 'Right Inferior Medial Buttock',
        232: 'Right Inferior Lateral Buttock',
        233: 'Right Gluteal Fold',
        234: 'Left Gluteal Fold',

        272: 'Front Top of Head',
        273: 'Right ForeHead',
        274: 'Left ForeHead',
        275: 'Right Eye',
        276: 'Left Eye',
        277: 'Right Face',
        278: 'Left Face',
        279: 'Mouth',
        280: 'Right Jaw',
        281: 'Left Jaw',
        282: 'Front Right Shoulder',
        284: 'Front Left Shoulder',
        285: 'Front Right Shoulder Joint',
        286: 'Right Chest',
        287: 'Left Chest',
        288: 'Front Left Shoulder Joint',
        289: 'Front Right Arm Over',
        290: 'Front Left Arm Over',
        291: 'Right Ribs',
        292: 'Left Ribs',
        293: 'Front Right Elbows',
        294: 'Right Upper Abdomen',
        295: 'Center Upper Abdomen',
        296: 'Left Upper Abdomen',
        297: 'Front Left Elbow',
        298: 'Front Right Arm Under',
        299: 'Right Lower Abdomen',
        300: 'Center Lower Abdomen',
        301: 'Left Lower Abdomen',
        302: 'Front Left Arm Under',
        303: 'Front Right Wrist',
        304: 'Right Hip',
        305: 'Genitalia',
        306: 'Left Hip',
        307: 'Front Left Wrist',
        308: 'Front Right Hand',
        309: 'Right Upper Thigh',
        310: 'Left Upper Thigh',
        311: 'Front Left Hand',
        312: 'Right Lower Thigh',
        313: 'Left Lower Thigh',
        314: 'Front Right Knee',
        315: 'Front Left Knee',
        316: 'Right Leg',
        317: 'Left Leg',
        318: 'Front Right Ankle',
        319: 'Front Left Ankle',
        320: 'Right Foot',
        321: 'Left Foot',

        66: 'Left Dorsal Wrist',
        67: 'Left Proximal Lateral Dorsal Hand',
        68: 'Left Proximal Medial Dorsal Hand',
        69: 'Left Distal Lateral Dorsal Hand',
        70: 'Left Distal Medial Dorsal Hand',
        71: 'Left Metocarpalphalangeal Joint of Thumb',
        72: 'Left Proximal Phalanx of Dorsal Thumb',
        73: 'Left Interphalangeal Crease of Thumb',
        74: 'Left Distal Phalanx of Dorsal Thumb',
        75: 'Left Metocarpalphalangeal Joint of Index Finger',
        76: 'Left Proximal Phalanx of Dorsal Index Finger',
        77: 'Left Proximal Interphalangeal Crease of Dorsal Index Finger',
        78: 'Left Middle Phalanx of Dorsal Index Finger',
        79: 'Left Distal Interphalangeal Crease of Index Finger',
        80: 'Left Distal Phalanx of Dorsal Index Finger',
        81: 'Left Metocarpalphalangeal Joint of Middle Finger',
        82: 'Left Proximal Phalanx of Dorsal Middle Finger',
        83: 'Left Proximal Interphalangeal Crease of Dorsal Middle Finger',
        84: 'Left Middle Phalanx of Dorsal Middle Finger',
        85: 'Left Distal Interphalangeal Crease of Middle Finger',
        86: 'Left Distal Phalanx of Dorsal Middle Finger',
        87: 'Left Metocarpalphalangeal Joint of Index Finger',
        88: 'Left Proximal Phalanx of Dorsal Ring Finger',
        89: 'Left Proximal Interphalangeal Crease of Dorsal Ring Finger',
        90: 'Left Middle Phalanx of Dorsal Ring Finger',
        91: 'Left Distal Interphalangeal Crease of Ring Finger',
        92: 'Left Distal Phalanx of Dorsal Ring Finger',
        93: 'Left Metocarpalphalangeal Joint of Little Finger',
        94: 'Left Proximal Phalanx of Dorsal Little Finger',
        95: 'Left Proximal Interphalangeal Crease of Dorsal Little Finger',
        96: 'Left Middle Phalanx of Dorsal Little Finger',
        97: 'Left Distal Interphalangeal Crease of Little Finger',
        98: 'Left Distal Phlanax of Dorsal Little Finger',
        99: 'Left Palmar Wrists',
        100: 'Left Hypothenar Eminence',
        101: 'Left Thenar Eminence',
        102: 'Left Palm',
        103: 'Left Palmar Digital Crease of Little Finger',
        104: 'Left Proximal Phalanx of Palmar Little Finger',
        105: 'Left Proximal Interphalangeal Crease of Palmar Little Finger',
        106: 'Left Middle Phalanx of Palmar Little Finger',
        107: 'Left Distal Interphalangeal Crease of Little Finger',
        108: 'Left Distal Phalanx of Palmar Little Finger',
        109: 'Left Palmar Digital Crease of Ring Finger',
        110: 'Left Proximal Phalanx of Palmar Ring Finger',
        111: 'Left Proximal Interphalangeal Crease of Palmar Ring Finger',
        112: 'Left Middle Phalanx of Palmar Ring Finger',
        113: 'Left Distal Interphalangeal Crease of Ring Finger',
        114: 'Left Distal Phalanx of Palmar Ring Finger',
        115: 'Left Palmar Digital Crease of Middle Finger',
        116: 'Left Proximal Phalanx of Palmar Middle Finger',
        117: 'Left Proximal Interphalangeal Crease of Palmar Middle Finger',
        118: 'Left Middle Phalanx of Palmar Middle Finger',
        119: 'Left Distal Interphalangeal Crease of Middle Finger',
        120: 'Left Distal Phalanx of Palmar Middle Finger',
        121: 'Left Palmar Digital Crease of Index Finger',
        122: 'Left Proximal Phalanx of Palmar Index Finger',
        123: 'Left Proximal Interphalangeal Crease of Palmar Index Finger',
        124: 'Left Middle Phalanx of Palmar Index Finger',
        125: 'Left Distal Interphalangeal Crease of Index Finger',
        126: 'Left Distal Phalanx of Palmar Index Finger',
        127: 'Left Palmar Digital Crease of Thumb',
        128: 'Left Proximal Phalanx of Palmar Thumb',
        129: 'Left Interphalangeal Crease of Thumb',
        130: 'Left Distal Phalanx of Palmar Thumb',

        175: 'Left Distal Anteromedial Leg',
        176: 'Left Distal Anterior Leg',
        177: 'Left Distal Anterolateral Leg',
        178: 'Left Medial Malleolus',
        179: 'Left Anteromedial Ankle',
        180: 'Left Anterior Ankle',
        181: 'Left Anterolateral Ankle',
        182: 'Left Proximal Medial Dorsal Foot',
        183: 'Left Proximal Mid Dorsal Foot',
        184: 'Left Proximal Lateral Dorsal Foot',
        185: 'Left Distal Medial Dorsal Foot',
        186: 'Left Distal Mid Dorsal Foot',
        187: 'Left Distal Lateral Dorsal Foot',
        188: 'Left Proximal Dorsal First Toe',
        189: 'Left Proximal Dorsal Second Toe',
        190: 'Left Proximal Dorsal Third Toe',
        191: 'Left Proximal Dorsal Fourth Toe',
        192: 'Left Proximal Dorsal Fifth Toe',
        193: 'Left Distal Dorsal First Toe',
        194: 'Left Distal Dorsal Second Toe',
        195: 'Left Distal Dorsal Third Toe',
        196: 'Left Distal Dorsal Fourth Toe',
        197: 'Left Distal Dorsal Fifth Toe',
        198: 'Left Distal Plantar First Toe',
        199: 'Left Distal Plantar Second Toe',
        200: 'Left Distal Plantar Third Toe',
        201: 'Left Distal Plantar Fourth Toe',
        202: 'Left Fifth Toe Tip',
        203: 'Left Proximal Plantar First Toe',
        204: 'Left Proximal Plantar Second Toe',
        205: 'Left Proximal Plantar Third Toe',
        206: 'Left Proximal Plantar Fourth Toe',
        207: 'Left Plantar Fifth Toe',
        208: 'Left First Metatarsal Phalangeal Joints (Ball of the Foot)',
        209: 'Left Plantar Second Metatarsal Phalangeal Joint',
        210: 'Left Plantar Third Metatarsal Phalangeal Joint',
        211: 'Left Plantar Fourth Metatarsal Phalangeal Joints',
        212: 'Left Plantar Fifth Metatarsal Phalangeal Joint',
        213: 'Left Distal Medial Mid Plantar Foot',
        214: 'Left Distal Lateral Mid Plantar Foot',
        215: 'Left Proximal Medial Plantar Foot',
        216: 'Left Proximal Lateral Mid Plantar Foot',
        217: 'Left Medial Heel',
        218: 'Left Lateral Heel',

        1: 'Right Palmar Wrist',
        2: 'Right Thenar Eminence',
        3: 'Right Hypothenar Eminence',
        4: 'Right Palmar Digital Crease of Thumb',
        5: 'Right Proximal Phalanx of Palmar Thumb',
        6: 'Right Interphalangeal Crease of Thumb',
        7: 'Right Distal Phalanx of Palmar Thumb',
        8: 'Right Palm',
        9: 'Right Palmar Digital Crease of Index Finger',
        10: 'Right Proximal Phalanx of Palmar Index Finger',
        11: 'Right Proximal Interphalangeal Crease of Palmar Index Finger',
        12: 'Right Middle Phalanx of Palmar Index Finger',
        13: 'Right Distal Interphalangeal Crease of Index Finger',
        14: 'Right Distal Phalanx of Palmar Index Finger',
        15: 'Right Palmar Digital Crease of Middle Finger',
        16: 'Right Proximal Phalanx of Palmar Middle Finger',
        17: 'Right Proximal Interphalangeal Crease of Palmar Middle Finger',
        18: 'Right Middle Phalanx of Palmar Middle Finger',
        19: 'Right Distal Interphalangeal Crease of Middle Finger',
        20: 'Right Distal Phalanx of Palmar Middle Finger',
        21: 'Right Palmar Digital Crease Ring Finger',
        22: 'Right Proximal Phalanx of Palmar Ring Finger',
        23: 'Right Proximal Interphalangeal Crease of Palmar Ring Finger',
        24: 'Right Middle Phalanx of Palmar Ring Finger',
        25: 'Right Distal Interphalangeal Crease of Ring Finger',
        26: 'Right Distal Phalanx of Palmar Ring Finger',
        27: 'Right Palmar Digital Crease of Little Finger',
        28: 'Right Proximal Phalanx of Palmar Little Finger',
        29: 'Right Proximal Interphalangeal Crease of Palmar Little Finger',
        30: 'Right Middle Phalanx of Palmar Little Finger',
        31: 'Right Distal Interphalangeal Crease of Little Finger',
        32: 'Right Distal Phalanx of Palmar Little Finger',
        33: 'Right Dorsal Wrist',
        34: 'Right Proximal Medial Dorsal Hand',
        35: 'Right Proximal Lateral Dorsal Hand',
        36: 'Right Distal Medial Dorsal Hand',
        37: 'Right Distal Lateral Dorsal Hand',
        38: 'Right Metocarpalphalangeal Joint of Little Finger',
        39: 'Right Proximal Phalanx of Dorsal Little Finger',
        40: 'Right Proximal Interphalangeal Joint of Dorsal Little Finger',
        41: 'Right Middle Phalanx of Dorsal Little Finger',
        42: 'Right Distal Interphalangeal Joint of Little Finger',
        43: 'Right Distal Phalanx of Dorsal Little Finger',
        44: 'Right Metocarpalphalangeal Joint of Ring Finger',
        45: 'Right Proximal Phalanx of Dorsal Ring Finger',
        46: 'Right Proximal Interphalangeal Joint of Dorsal Ring Finger',
        47: 'Right Middle Phalanx of Dorsal Ring Finger',
        48: 'Right Distal Interphalangeal Joint of Ring Finger',
        49: 'Right Distal Phalanx of of Dorsal Ring Finger',
        50: 'Right Metocarpalphalangeal Joint of Middle Finger',
        51: 'Right Proximal Phalanx of Dorsal Middle Finger',
        52: 'Right Proximal Interphalangeal Joint of Right Middle Finger',
        53: 'Right Middle Phalanx of Dorsal Middle Finger',
        54: 'Right Distal Interphalangeal Joint of Middle Finger',
        55: 'Right Distal Phalanx of Dorsal Middle Finger',
        56: 'Right Metocarpalphalangeal Joint of Index Finger',
        57: 'Right Proximal Phalanx of Dorsal Index Finger',
        58: 'Right Proximal Interphalangeal Joint of Dorsal Index Finger',
        59: 'Right Middle Phalanx of Dorsal Index Finger',
        60: 'Right Distal Interphalangeal Joint of Index Finger',
        61: 'Right Distal Phalanx of Dorsal Index Finger',
        62: 'Right Metocarpalphalangeal Joint of Thumb',
        63: 'Right Proximal Phalanx of Dorsal Thumb',
        64: 'Right Interphalangeal Joint of Thumb',
        65: 'Right Distal Phalanx of Dorsal Thumb',

        131: 'Right Distal Plantar First Toe',
        132: 'Right Distal Plantar Second Toe',
        133: 'Right Distal Plantar Third Toe',
        134: 'Right Distal Plantar Fourth Toe',
        135: 'Right Fifth Toe Tip',
        136: 'Right Plantar Fifth Toe',
        137: 'Right Proximal Plantar Fourth Toe',
        138: 'Right Proximal Plantar Third Toe',
        139: 'Right Proximal Plantar Second Toe',
        140: 'Right Proimal Plantar First Toe',
        141: 'Right Plantar Fifth Metatarsal Phalangeal Joint',
        143: 'Right Plantar Fourth Metatarsal Phalangeal Joint Right Dorsal Third Metatarsal Phalangeal Joint',
        144: 'Right Plantar Second Metatarsal Phalangeal Joint',
        145: 'Right Dorsal First Metatarsal Phalangeal Joints (Bal of the Foot)',
        146: 'Right Distal Lateral Mid Plantar Foot',
        147: 'Right Distal Medial Mid Plantar Foot',
        148: 'Right Proximal Lateral Mid Plantar Foot',
        149: 'Right Proximal Medial Plantar Foot',
        150: 'Right Lateral Heel',
        151: 'Right Medial Heel',
        152: 'Right Distal Anterolateral Leg',
        153: 'Right Distal Anteior Leg',
        154: 'Right Distal Anteromedial Leg',
        155: 'Right Anterolateral Ankle',
        156: 'Right Anterior Ankle',
        157: 'Right Anteromedial Ankle',
        158: 'Right Medial Malleolus',
        159: 'Right Proximal Lateral Dorsal Foot',
        160: 'Right Proximal Mid Dosal Foot',
        161: 'Right Proximal Medial Dorsal Foot',
        162: 'Right Distal Lateral Dorsal Foot',
        163: 'Right Distal Mid Dorsal Foot',
        164: 'Right Distal Lateral Dorsal Foot',
        165: 'Right Proximal Dorsal Fifth Toe',
        166: 'Right Proximal Dorsal Fourth Toe',
        167: 'Right Proximal Dorsal Third Toe',
        168: 'Right Proximal Dorsal Second Toe',
        169: 'Right Proximal Dorsal First Toe',
        170: 'Right Distal Dorsal Fifth Toe',
        171: 'Right Distal Dorsal Fourth Toe',
        172: 'Right Distal Dorsal Third Toe',
        173: 'Right Distal Dorsal Second Toe',
        174: 'Right Distal Dorsal First Toe'

    }

    return map[id]



def get_wound_type_by_id(id):
    return {
        1:'diabetic',
        2:None,
        3:'pressure',
        4:'surgical',
        5:'venous'
    }.get(id)